# Generated by Django 5.1.1 on 2024-09-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=100, verbose_name="email клиента"),
                ),
                (
                    "client_name",
                    models.CharField(max_length=150, verbose_name="имя клиента"),
                ),
                ("description", models.TextField(verbose_name="комментарий")),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="тема письма"),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mailing_name",
                    models.CharField(max_length=255, verbose_name="имя рассылки"),
                ),
                (
                    "first_send_date_time",
                    models.DateTimeField(verbose_name="дата и время первой рассылки"),
                ),
                (
                    "next_send_date_time",
                    models.DateTimeField(
                        verbose_name="дата и время следующей рассылки"
                    ),
                ),
                (
                    "last_send_date_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="дата и время последней рассылки",
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            ("Раз в минуту", "Раз в минуту"),
                            ("Раз в день", "Раз в день"),
                            ("Раз в неделю", "Раз в неделю"),
                            ("Раз в месяц", "Раз в месяц"),
                        ],
                        default="Раз в минуту",
                        verbose_name="периодичность отправки",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            ("COMPLETED", "Завершена"),
                            ("CREATED", "Создана"),
                            ("STARTED", "Запущена"),
                        ],
                        default="Создана",
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        blank=True, to="mailing.client", verbose_name="клиенты"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.message",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_attempt_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="последняя попытка"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "успешно"), ("failed", "неуспешно")],
                        max_length=50,
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "server_response",
                    models.CharField(
                        max_length=150, verbose_name="ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
            },
        ),
    ]
