# Generated by Django 5.1.1 on 2024-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="period",
            field=models.IntegerField(
                choices=[
                    (60, "Раз в минуту"),
                    (1440, "Раз в день"),
                    (10080, "Раз в неделю"),
                    (302400, "Раз в месяц"),
                ],
                default=60,
                verbose_name="периодичность отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.IntegerField(
                choices=[
                    ("COMPLETED", "Завершена"),
                    ("CREATED", "Создана"),
                    ("STARTED", "Запущена"),
                ],
                default=1,
                verbose_name="статус рассылки",
            ),
        ),
    ]
