# Generated by Django 5.1.1 on 2024-09-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_period_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="last_send_date_time",
            field=models.DateTimeField(
                default=None, verbose_name="дата и время последней рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="period",
            field=models.IntegerField(
                choices=[
                    (1440, "Раз в день"),
                    (10080, "Раз в неделю"),
                    (302400, "Раз в месяц"),
                ],
                default=1440,
                verbose_name="периодичность отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Завершена"),
                    ("CREATED", "Создана"),
                    ("STARTED", "Запущена"),
                ],
                default=1,
                max_length=150,
                verbose_name="статус рассылки",
            ),
        ),
    ]
