# Generated by Django 5.1.1 on 2024-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_send_date_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата и время первой рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_send_date_time",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="дата и время последней рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="next_send_date_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата и время следующей рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="period",
            field=models.CharField(
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                default="Раз в день",
                max_length=150,
                verbose_name="периодичность отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Завершена"),
                    ("CREATED", "Создана"),
                    ("STARTED", "Запущена"),
                ],
                default="Создана",
                max_length=150,
                verbose_name="статус рассылки",
            ),
        ),
    ]
