# Generated by Django 4.2.2 on 2024-09-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_client_owner_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("deactivate_mailing", "Can deactivate mailing"),
                    ("view_all_mailings", "Can view all mailings"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
